# Generated by Django 5.2 on 2025-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills associated with the user', related_name='user_skills', to='skills.skill'),
        ),
    ]
