# Generated by Django 5.2.1 on 2025-06-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dream_role',
            field=models.CharField(blank=True, help_text="User's desired career goal", max_length=100),
        ),
    ]
