# Generated by Django 5.2.1 on 2025-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dream_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth user ID', max_length=100, null=True, unique=True),
        ),
    ]
