# Generated by Django 5.0.1 on 2025-05-07 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_courseskill_unique_together'),
        ('users', '0002_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dream_job',
            field=models.ForeignKey(blank=True, help_text="User's target career role", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspiring_users', to='skills.careerrole'),
        ),
    ]
