# Generated by Django 5.0.1 on 2025-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dream_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Professional summary and background')),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_profile', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
