# Generated by Django 5.0.1 on 2025-05-08 17:11

from django.db import migrations

def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
