# Generated by Django 5.2.1 on 2025-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_theme_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High school'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('working_professional', 'Working professional'), ('other', 'Other')], help_text='Highest level of education (nullable)', max_length=32, null=True),
        ),
    ]
