# Generated by Django 5.2.1 on 2026-05-22 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique session identifier', unique=True)),
                ('original_query', models.TextField(help_text="The user's original query")),
                ('classification_category', models.CharField(db_index=True, help_text='Query classification category', max_length=50)),
                ('rewritten_query', models.TextField(blank=True, help_text='The rewritten query for retrieval', null=True)),
                ('pipeline_name', models.CharField(db_index=True, help_text='Retrieval pipeline used', max_length=255)),
                ('retrieved_chunk_count', models.IntegerField(default=0, help_text='Number of chunks retrieved')),
                ('generated_answer', models.TextField(help_text='The initial generated answer')),
                ('final_answer', models.TextField(help_text='The final answer after verification')),
                ('faithfulness_score', models.FloatField(blank=True, help_text='Verification faithfulness score (0-1)', null=True)),
                ('confidence_score', models.FloatField(blank=True, db_index=True, help_text='Final confidence score (0-1)', null=True)),
                ('confidence_interpretation', models.CharField(db_index=True, default='', help_text='Confidence interpretation (HIGH_CONFIDENCE/MODERATE_CONFIDENCE/LOW_CONFIDENCE)', max_length=20)),
                ('unverified', models.BooleanField(db_index=True, default=False, help_text='Whether answer could not be verified')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('total_latency', models.FloatField(help_text='Total execution time in milliseconds')),
                ('latency_breakdown', models.JSONField(default=dict, help_text='Breakdown of latencies by stage')),
                ('full_result', models.JSONField(default=dict, help_text='Complete ReasoningResult as JSON')),
                ('subject_id', models.IntegerField(db_index=True, help_text='Subject ID that was searched')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Session creation timestamp')),
            ],
            options={
                'verbose_name': 'Reasoning Session',
                'verbose_name_plural': 'Reasoning Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pipeline_name', 'created_at'], name='reasoning_pipe_created_idx'), models.Index(fields=['confidence_score', 'created_at'], name='reasoning_conf_created_idx'), models.Index(fields=['classification_category', 'created_at'], name='reasoning_class_created_idx'), models.Index(fields=['subject_id', 'created_at'], name='reasoning_subj_created_idx'), models.Index(fields=['unverified', 'created_at'], name='reasoning_unverif_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReasoningSessionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.IntegerField(help_text='Original chunk ID from retrieval')),
                ('chunk_text', models.TextField(help_text='The chunk content')),
                ('chunk_index', models.IntegerField(help_text='Position in original document')),
                ('material_id', models.IntegerField(help_text='Source material ID')),
                ('material_name', models.CharField(help_text='Source material name', max_length=255)),
                ('similarity_score', models.FloatField(help_text='Initial similarity score')),
                ('reranking_score', models.FloatField(blank=True, help_text='Score after reranking', null=True)),
                ('used_in_retry', models.BooleanField(default=False, help_text='Whether chunk was used in a retry attempt')),
                ('session', models.ForeignKey(help_text='Parent reasoning session', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='reasoning.reasoningsession')),
            ],
            options={
                'verbose_name': 'Reasoning Session Chunk',
                'verbose_name_plural': 'Reasoning Session Chunks',
                'ordering': ['-similarity_score'],
            },
        ),
    ]
