# Generated by Django 4.2.18 on 2025-02-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the course', max_length=200)),
                ('platform', models.CharField(choices=[('coursera', 'Coursera'), ('udemy', 'Udemy'), ('linkedin', 'LinkedIn Learning'), ('pluralsight', 'PluralSight'), ('other', 'Other Platform')], help_text='Platform hosting the course', max_length=50)),
                ('resource_url', models.URLField(help_text='Direct link to the course')),
                ('description', models.TextField(blank=True, help_text='Brief description of what the course covers')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Course difficulty level', max_length=20)),
                ('clicks', models.IntegerField(default=0, help_text='Number of times this resource was accessed')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this resource was accessed')),
                ('related_skills', models.ManyToManyField(help_text='Skills this course helps develop', to='skills.skill')),
            ],
        ),
    ]
