# Generated by Django 5.0.1 on 2025-05-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_achievement_learningstreak_courseprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('podcast', 'Podcast'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=20)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_saved'],
                'indexes': [models.Index(fields=['user', 'resource_type'], name='learning_sa_user_id_126deb_idx'), models.Index(fields=['date_saved'], name='learning_sa_date_sa_989fa6_idx')],
            },
        ),
    ]
