# Generated by Django 5.2.1 on 2025-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, help_text='External link to the course (e.g., Coursera, Udemy, etc.)', null=True),
        ),
    ]
