# Generated by Django 5.2.1 on 2025-06-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_course_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='notes',
        ),
        migrations.DeleteModel(
            name='LearningStreak',
        ),
    ]
