# Generated by Django 5.0.1 on 2025-05-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_savedresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='notes',
            field=models.TextField(blank=True, help_text='Current notes about this course'),
        ),
        migrations.CreateModel(
            name='CourseProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_history', to='learning.courseprogress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
