# Generated by Django 5.2.1 on 2025-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_courseprogress_notes_delete_learningstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Is this course free?'),
        ),
    ]
