# Generated by Django 5.0.1 on 2025-05-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_courseprogress_notes_courseprogressnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='progress_percent',
        ),
    ]
