# Generated by Django 5.2.1 on 2025-07-29 15:54

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    """Load initial courses, achievements, and learning resources"""
    call_command('loaddata', 'initial_data', app_label='learning')


def reverse_load_initial_data(apps, schema_editor):
    """Remove the loaded data (optional - for rollback)"""
    Course = apps.get_model('learning', 'Course')
    Achievement = apps.get_model('learning', 'Achievement')
    LearningResource = apps.get_model('learning', 'LearningResource')
    
    Course.objects.all().delete()
    Achievement.objects.all().delete()
    LearningResource.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_course_is_free'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_load_initial_data),
    ]
