# Generated by Django 5.0.1 on 2025-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(help_text='Emoji or icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(help_text='Type of achievement (courses_completed, streak, skill_level, total_hours)', max_length=50),
        ),
    ]
