# Generated by Django 5.2.1 on 2025-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_question_alter_quizattempt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='dynamic_questions',
            field=models.JSONField(blank=True, help_text='Stores dynamically generated questions for this attempt', null=True),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='uses_dynamic_questions',
            field=models.BooleanField(default=False, help_text='True if this attempt uses dynamically generated questions'),
        ),
    ]
