# Generated by Django 5.2.1 on 2025-06-26 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_add_dynamic_questions_to_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(upload_to='subject_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'mp4', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('DOC', 'Word Document (Legacy)'), ('VIDEO', 'Video File')], max_length=10),
        ),
    ]
