# Generated by Django 5.2.1 on 2025-07-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_add_word_document_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='subjects.subjectmaterial'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_quiz_questions', to='subjects.subjectmaterial'),
        ),
    ]
