# Generated by Django 5.2.1 on 2025-07-08 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_chatsession_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'subject', 'is_active'], name='subjects_ch_user_id_5d84b7_idx'),
        ),
    ]
