# Generated by Django 5.2.1 on 2025-07-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_remove_chat_session_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchunk',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of embedding generation for this chunk', max_length=10),
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='contentchunk',
            index=models.Index(fields=['embedding_status'], name='subjects_co_embeddi_dce7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='contentchunk',
            index=models.Index(fields=['material', 'embedding_status'], name='subjects_co_materia_a450de_idx'),
        ),
    ]
