# Generated by Django 5.2.1 on 2025-07-09 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_add_embedding_status_to_contentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity timestamp for timeout tracking'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
