# Generated by Django 5.2.1 on 2025-07-28 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_add_session_timeout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(upload_to='subject_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('DOC', 'Word Document (Legacy)'), ('VIDEO', 'Video File'), ('AUDIO', 'Audio File')], max_length=10),
        ),
    ]
