# Generated by Django 5.2.1 on 2025-07-29 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_alter_subjectmaterial_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(help_text='MD5 hash of normalized question text', max_length=64)),
                ('question_text', models.TextField(help_text='Original question text for debugging and analytics')),
                ('response_data', models.JSONField(help_text='Complete RAG response data including response, metadata, and retrieved chunks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this cache entry expires and should be cleaned up')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cached response has been accessed')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this cache entry was accessed')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_responses', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cached Response',
                'verbose_name_plural': 'Cached Responses',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user', 'subject', 'question_hash'], name='subjects_ca_user_id_b9f027_idx'), models.Index(fields=['expires_at'], name='subjects_ca_expires_8d578b_idx'), models.Index(fields=['hit_count'], name='subjects_ca_hit_cou_36a802_idx'), models.Index(fields=['last_accessed'], name='subjects_ca_last_ac_52c8a5_idx')],
                'unique_together': {('user', 'subject', 'question_hash')},
            },
        ),
    ]
