# Generated by Django 5.2.1 on 2025-07-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_cachedresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='material',
            field=models.ForeignKey(blank=True, help_text='The material this quiz was generated from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='subjects.subjectmaterial'),
        ),
    ]
