# Generated by Django 4.2.18 on 2025-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the skill')),
                ('category', models.CharField(blank=True, help_text='Category of skill (e.g., Technical, Soft Skills, etc.)', max_length=50)),
            ],
        ),
    ]
