# Generated by Django 5.2 on 2025-04-18 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this skill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills_direct', to=settings.AUTH_USER_MODEL),
        ),
    ]
