# Generated by Django 5.2 on 2025-04-18 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Name of the skill', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'user')},
        ),
    ]
