# Generated by Django 5.2 on 2025-04-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_name_alter_skill_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the career role', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role and responsibilities')),
                ('category', models.CharField(blank=True, help_text='Category of role (e.g., Development, Data Science, Design)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the course', max_length=200)),
                ('provider', models.CharField(help_text='Provider or platform offering the course', max_length=100)),
                ('url', models.URLField(help_text='Link to the course')),
                ('description', models.TextField(blank=True, help_text='Description of the course')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Difficulty level of the course', max_length=20)),
                ('duration', models.CharField(blank=True, help_text="Estimated duration to complete (e.g., '4 weeks', '10 hours')", max_length=50)),
                ('is_free', models.BooleanField(default=False, help_text='Whether the course is free')),
                ('skills_taught', models.ManyToManyField(blank=True, help_text='Skills taught by this course', related_name='courses', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the skill taught', max_length=100)),
                ('proficiency_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Level of proficiency taught for this skill', max_length=20)),
                ('course', models.ForeignKey(help_text='The course teaching this skill', on_delete=django.db.models.deletion.CASCADE, to='skills.course')),
                ('skill', models.ForeignKey(blank=True, help_text='Reference to the skill being taught', null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'unique_together': {('course', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the required skill', max_length=100)),
                ('importance', models.CharField(choices=[('essential', 'Essential'), ('important', 'Important'), ('nice_to_have', 'Nice to Have')], default='important', help_text='Importance level of this skill for the role', max_length=20)),
                ('role', models.ForeignKey(help_text='The career role', on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='skills.careerrole')),
            ],
            options={
                'unique_together': {('role', 'skill_name')},
            },
        ),
    ]
