# Generated by Django 5.0.1 on 2025-05-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_courseskill_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='proficiency_level',
        ),
    ]
