# Generated by Django 5.2.1 on 2026-05-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name for this experiment', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of what this experiment tests')),
                ('pipeline_config', models.JSONField(help_text='Pipeline configuration for this experiment')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this experiment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this experiment was created')),
            ],
            options={
                'verbose_name': 'Retrieval Experiment',
                'verbose_name_plural': 'Retrieval Experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalPipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name for this pipeline configuration', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of this pipeline')),
                ('config', models.JSONField(help_text='Full pipeline configuration as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this configuration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this configuration was last updated')),
            ],
            options={
                'verbose_name': 'Retrieval Pipeline Configuration',
                'verbose_name_plural': 'Retrieval Pipeline Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(db_index=True, help_text='Name of the pipeline configuration used', max_length=255)),
                ('query', models.TextField(help_text='The search query')),
                ('top_k', models.IntegerField(help_text='The top-K setting used for retrieval')),
                ('retrieved_chunk_count', models.IntegerField(help_text='Number of chunks retrieved')),
                ('mean_similarity_score', models.FloatField(help_text='Average similarity score of retrieved chunks')),
                ('top_score', models.FloatField(help_text='Highest similarity score among retrieved chunks')),
                ('reranking_applied', models.BooleanField(default=False, help_text='Whether reranking was applied')),
                ('reranker_used', models.CharField(blank=True, help_text='The reranker used if reranking was applied', max_length=255, null=True)),
                ('total_latency_ms', models.FloatField(help_text='Total execution time in milliseconds')),
                ('embedding_latency_ms', models.FloatField(help_text='Time spent on query embedding in milliseconds')),
                ('search_latency_ms', models.FloatField(help_text='Time spent on vector search in milliseconds')),
                ('reranking_latency_ms', models.FloatField(blank=True, help_text='Time spent on reranking in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this metric was recorded')),
            ],
            options={
                'verbose_name': 'Retrieval Metric',
                'verbose_name_plural': 'Retrieval Metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pipeline_name', 'created_at'], name='retrieval_r_pipelin_c7e78c_idx'), models.Index(fields=['created_at'], name='retrieval_r_created_6519d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetrievalExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='The search query used')),
                ('subject_id', models.IntegerField(blank=True, help_text='The subject ID that was searched', null=True)),
                ('results', models.JSONField(help_text='Retrieved chunks as JSON')),
                ('metrics', models.JSONField(help_text='Timing and scoring metrics as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this result was recorded')),
                ('experiment', models.ForeignKey(help_text='The experiment this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='retrieval.retrievalexperiment')),
            ],
            options={
                'verbose_name': 'Retrieval Experiment Result',
                'verbose_name_plural': 'Retrieval Experiment Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['experiment', 'created_at'], name='retrieval_r_experim_38f72f_idx')],
            },
        ),
    ]
